### ISSUE TITLE
Configure In Game Tickets

### ISSUE THREAD

**Issue by MrDieSeL101** [WolfeLabs/Project-Drop-Zone#102]

**Comment by ZwinkaDink** [comment]
description my dude

**Comment by MrDieSeL101** [comment]
Umm I wanna make the in game tickets for cops match the ticket bookarino that nadell sent

**Comment by ZwinkaDink** [comment]
that is a tall order you will need a GUI for the ticket book( a tall order on its own) then we will need to link it in to the current law system
