### ISSUE TITLE
Edit Civ Spawns

### ISSUE THREAD

**Issue by MrDieSeL101** [WolfeLabs/Project-Drop-Zone#11]

**Comment by MrDieSeL101** [comment]
This is not super high priority. I have it set currently so that positions are saved when you log out. they only reset on server restart

**Comment by ryannadell** [comment]
Can you elaborate more so on this ticket, do you wish for expanded civilian spawns or are you talking about something different.

**Comment by ryannadell** [comment]
not my issue
