### ISSUE TITLE
Rebel garage shop doesn't allow you to pull out a helicopter from the garage, only vehicles.

### ISSUE THREAD

**Issue by FurryDev** [WolfeLabs/Project-Drop-Zone#130]
When accessing the garage in rebel, you only get vehicles you've bought as seen here. https://gyazo.com/baf91dd01d627f2a8d1c060a14906574

**Comment by ryannadell** [comment]
maybe go to the other vendor to your back left and use the vehicle garage where you can buy choppers from 4hed
