### ISSUE TITLE
Add Image To Splash Screen Instead of Text

### ISSUE THREAD

**Issue by MrDieSeL101** [WolfeLabs/Project-Drop-Zone#14]
![DZ2](https://user-images.githubusercontent.com/83042314/116091376-bfd7b700-a672-11eb-9806-79e52632fab2.png)

**Comment by ZwinkaDink** [comment]
![20210426173734_1](https://user-images.githubusercontent.com/22672660/116154166-524d7a00-a6b6-11eb-8fcb-8389906e8d65.jpg)
 done

**Comment by MrDieSeL101** [comment]
Thats cool, but i meant here

https://www.baka.wtf/u/9bV2QN3LTr.png

**Comment by MrDieSeL101** [comment]
Thats nice but i meant here 
![splash](https://user-images.githubusercontent.com/83042314/116247933-579fd880-a739-11eb-9274-dfa08d258d55.png)

**Comment by ZwinkaDink** [comment]
d7be5e44a3a3589098b3b0e9fa59572f5a81f3f1

**Comment by MrDieSeL101** [comment]
WHy is this reopened?
