### ISSUE TITLE
whitelist access for ems/pd heads

### ISSUE THREAD

**Issue by MrDieSeL101** [WolfeLabs/Project-Drop-Zone#140]

**Comment by MrDieSeL101** [comment]
how can we do this

**Comment by ZwinkaDink** [comment]
explain further

**Comment by MrDieSeL101** [comment]
i need pd command staff and ems command staff to be able to whitelist people

**Comment by MrDieSeL101** [comment]
prefferably without them having to login to the box

**Comment by ZwinkaDink** [comment]
if you trust your heads we can set them up a login for the DATABASE and restrict what they can edit
