### ISSUE TITLE
ADD COP LIGHT JUSTIN

### ISSUE THREAD

**Issue by MrDieSeL101** [WolfeLabs/Project-Drop-Zone#18]
TO FRONT OF CAR <3

**Comment by ZwinkaDink** [comment]
![20210501174521_2](https://user-images.githubusercontent.com/22672660/116795913-58709b80-aaa6-11eb-8376-89ac68d87179.jpg)
![20210501174521_1](https://user-images.githubusercontent.com/22672660/116795914-58709b80-aaa6-11eb-8c88-9c7822c12f30.jpg)

**Comment by ZwinkaDink** [comment]
my light system is in can see the lights pretty good during the day
