### ISSUE TITLE
PD Training Grounds In Salt Flats

### ISSUE THREAD

**Issue by MrDieSeL101** [WolfeLabs/Project-Drop-Zone#26]
I want something like we had on LNS. 
- [ ] Office Building 
- [ ] Vehicle Course
- [ ] Short Distance Firing Range
- [ ] Long Distance Firing Range(300m-1km)
- [ ] Shoot Houses 
- [ ] Cop shop (clothing, weapons, VItems)
- [ ] Cop vehicle shop
- [ ] Cop Heli Shop
- [ ] Spawn Point Added To Spawn Menu
- [ ] Ample Space For Helicopters to Land 
- [ ] Space to train pilots
- [ ] Large Central Gathering Area (Briefing Area)
Possibly more as I get more Ideas

**Comment by ryannadell** [comment]
Salt flats stinky, moved to near kavala made cute n shit
