### ISSUE TITLE
Kavala PD Revamp

### ISSUE THREAD

**Issue by MrDieSeL101** [WolfeLabs/Project-Drop-Zone#30]
- [ ] Remove Tree and Phone Booth
  ![pdremove2](https://user-images.githubusercontent.com/83042314/116261423-a0f62500-a745-11eb-809e-00cc2c9b8ea1.png)
- [ ] Remove two stupid ass buildings
![pdremove1](https://user-images.githubusercontent.com/83042314/116261450-a5bad900-a745-11eb-911c-420717433bd7.png)

- [ ] Add a Holding/Processing Area Where the Tree And Phone Booth Used To Be With Lights Preferably
- [ ] Add Parking Spots (Shown Below)
![ParkingSPotscircled](https://user-images.githubusercontent.com/83042314/116262116-44473a00-a746-11eb-9766-9c68a7efb4a4.jpg)
- [ ]Add Lights Here
![pdlights](https://user-images.githubusercontent.com/83042314/116262356-76f13280-a746-11eb-9a8f-636856cd6a7c.png)
 Subject to Change...

**Comment by ryannadell** [comment]
Finished, trade secret gate installed with ADT security systems in place, call 1 (800) 521-1734 for any questions comments or concerns.
