### ISSUE TITLE
Nadell Sucks 

### ISSUE THREAD

**Issue by MrDieSeL101** [WolfeLabs/Project-Drop-Zone#38]
![nadellsucks](https://user-images.githubusercontent.com/83042314/116308341-61473180-a775-11eb-8efe-db2ffdd10d81.jpg)
fix please

**Comment by ryannadell** [comment]
fuk u

**Comment by MrDieSeL101** [comment]
no u

**Comment by ryannadell** [comment]
Also Ryan Add ATM's / ATM function to various vendors at air garage and such

**Comment by ryannadell** [comment]
Done, worked in with other updates will push with Justin's drug update as I compiled the resource points and vendors on current update aswell.
