### ISSUE TITLE
Training Ground Houses Are Buyable

### ISSUE THREAD

**Issue by MrDieSeL101** [WolfeLabs/Project-Drop-Zone#41]
Is there a way we can disable the ability to buy the houses at PD training ground?

**Comment by ryannadell** [comment]
Yes there is I just gotta remember how to do it since I thought I had them unbuyable when I used that training ground last but I guess that code doesnt work or it didnt transfer properly, will look into it ASAP.

**Comment by MrDieSeL101** [comment]
I have bought the ones that are buyable for now. I can just wipe the house part of the database whenever ur ready to push a fix
