### ISSUE TITLE
market move

### ISSUE THREAD

**Issue by ZwinkaDink** [WolfeLabs/Project-Drop-Zone#43]
need the market in kavala moved to square and como tent replaced

**Comment by ryannadell** [comment]
Also Ryan add lights to all proccessing buildings and build gang hideouts up

**Comment by ryannadell** [comment]
Fix atm at main airfield

**Comment by ryannadell** [comment]
Only felt like doing half of this at the moment, square fixed with all vendors there, atm at airfield *Probably* fixed, had to eyeball it through a stream acrossed my yard with a water house, gang hideouts not lit or built but not a huge issue atm will deal with later processing buildings lit.
