### ISSUE TITLE
more medic stuff

### ISSUE THREAD

**Issue by ZwinkaDink** [WolfeLabs/Project-Drop-Zone#46]
find more QOL items to make EMS enjoyable

**Comment by ZwinkaDink** [comment]
organ delivery to hospitals

**Comment by ZwinkaDink** [comment]
knock out drugs

**Comment by MrDieSeL101** [comment]
> organ delivery to hospitals

yes

**Comment by MrDieSeL101** [comment]
> knock out drugs

ketamine?

**Comment by ZwinkaDink** [comment]
> 
> 
> > knock out drugs
> 
> ketamine?

do we want to make it a player interaction function

**Comment by ZwinkaDink** [comment]
added morphine injecters to EMS
