### ISSUE TITLE
Restart Script doing that thing again

### ISSUE THREAD

**Issue by ryannadell** [WolfeLabs/Project-Drop-Zone#57]
Restart script is speaking baguette again

**Comment by MrDieSeL101** [comment]
I'll fix this when I get home

**Comment by ZwinkaDink** [comment]
alex must have touched it again

**Comment by ZwinkaDink** [comment]
there is no way you tarded it had over 7 terminals up when i got on box

**Comment by MrDieSeL101** [comment]
I didn't touch haven't been on my computer today at all

**Comment by ZwinkaDink** [comment]
seems to be good now maybe had server lag when server went to restart
