### ISSUE TITLE
Confirm flip vehicle works and possibly see about adding a push vehicle funtion in addition

### ISSUE THREAD

**Issue by ryannadell** [WolfeLabs/Project-Drop-Zone#58]
Like with boats you can scroll and click push, however with unflipping a car it tends to get stuck more in some cases and adding another feature for the vehicle unstuck/flip would be to push it, or essentially teleport it 1-5 meters in your chosen direction.

**Comment by ZwinkaDink** [comment]
flip does work
but i cal look for a push ro make one my own

**Comment by MrDieSeL101** [comment]
dont really think we need  a push script. only way i see that being useful is if the push action is only available if you have keys to the car. i can see people abusing it if its not set up that way
