### ISSUE TITLE
Automatic Scheduled Server Restarts

### ISSUE THREAD

**Issue by MrDieSeL101** [WolfeLabs/Project-Drop-Zone#6]
Make Server Restart Automatically at predetermined intervals (I.E. Server restarts every 4 hours)
Give Warning of restart at 30, 15, 10, 5, 3, 2, 1, minutes before restart
Kick All Players and lock server 30 seconds before restart

**Comment by ZwinkaDink** [comment]
this is currently running and being tested on server
