### ISSUE TITLE
Configure All Weapon Shops

### ISSUE THREAD

**Issue by MrDieSeL101** [WolfeLabs/Project-Drop-Zone#7]

**Comment by MrDieSeL101** [comment]
**COP**
- [ ] Cop Weapons
- [ ] Cop Magazines
- [ ] Cop Accessories

**CIV**
- [ ] Civ Weapons
- [ ] Civ Mags
- [ ] Civ Accs

**REBEL**
- [ ] Reb Weapons
- [ ] Reb Mags
- [ ] Reb Accs

**Comment by ryannadell** [comment]
Fuck you diesel, check prices I guess
