### ISSUE TITLE
Configure All Clothing Shops

### ISSUE THREAD

**Issue by MrDieSeL101** [WolfeLabs/Project-Drop-Zone#8]

**Comment by MrDieSeL101** [comment]
Cop Clothing 
- [ ] Outfits
- [ ] Vests
- [ ] Glasses
- [ ] Hats
- [ ] Bags

Civ Clothing
- [ ] Outfits
- [ ] Vests
- [ ] Glasses
- [ ] Hats
- [ ] Bags

Reb Clothing
- [ ] Outfits
- [ ] Vests
- [ ] Glasses
- [ ] Hats
- [ ] Bags

**Comment by ryannadell** [comment]
Self adding myself since diesel is lazy

**Comment by MrDieSeL101** [comment]
Smoochies

**Comment by ryannadell** [comment]
All but rebel clothes done on my side will finish them after work tomorrow and then move to next config *I GUESS*

**Comment by ryannadell** [comment]
Done, it isnt being pushed cause ima probably end up doing ALL OF THE FUCKING CONFIGS, that being said I found my vindic repository so I have all of them files.
