### ISSUE TITLE
Add A Seperate vendor for air vehicles at rebel outposts

### ISSUE THREAD

**Issue by MrDieSeL101** [WolfeLabs/Project-Drop-Zone#80]
so i basically want the rebel outposts to have a vendor for land vehicles, and then a seperate one for helicopters and id like to have a few marked heli pads.
if possible, adding garages to both the land vehicle vendor and air vehicle vendor would be very nice

**Comment by ryannadell** [comment]
If you can convince me why I will do it, aside form adding marked heli pads and livining up the place I see no point to adding more shops when they aren't being utilized.

**Comment by ryannadell** [comment]
Spoke with Ticket creator and stated that this was not big brain, regardless spruced up rebel op and added shit
