### ISSUE TITLE
Modular Store Robberies

### ISSUE THREAD

**Issue by MrDieSeL101** [WolfeLabs/Project-Drop-Zone#81]
https://bytex.market/products/item/lg5y2eapmtzdoghudnqu/Robbery%20System#img473

**Comment by MrDieSeL101** [comment]
or this
 https://www.altisliferpg.com/topic/5-basics-mrkrakens-gas-station-robbery-script/?tab=comments#comment-5

**Comment by ryannadell** [comment]
this addAction["Rob the Gas Station",life_fnc_robstore];

**Comment by ryannadell** [comment]
FUK YOU
