### ISSUE TITLE
IDK WHAT TO CALL THIS

### ISSUE THREAD

**Issue by MrDieSeL101** [WolfeLabs/Project-Drop-Zone#83]
CAN U FIX THIS PLEASE LMAO 

![OOPS](https://user-images.githubusercontent.com/83042314/117020189-35bbce00-acc4-11eb-9c53-339dbfecb5a7.png)

**Comment by MrDieSeL101** [comment]
i jumped into the table and it did this lolol

**Comment by ryannadell** [comment]
No Jumpy on table ez fix
